AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: provided.al2023
    Architectures:
      - x86_64
    Timeout: 10
    MemorySize: 512
    Environment:
      Variables:
        MONGODB_URI: mongodb+srv://portfolio_access_user:wF2huzzJokGcC1hZ@personal-cluster0.zs0hkbl.mongodb.net/?appName=Personal-Cluster0

Resources:
  ApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: manochy-api/
      Handler: bootstrap

      Events:
        Api:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: ANY
Metadata:
  BuildMethod: makefile
